/**
 * 角色配置 — 器灵六族
 * 铸魂族(青铜) | 瓷灵族(瓷器) | 玉魄族(玉器) | 锋芒族(兵器) | 墨魂族(书画) | 金翎族(金银)
 */

// Characters
const Characters = {
    starter: { id: 'char_001', name: '青铜小鼎', emoji: '🏺', rarity: 'N', description: '铸魂族的初醒器灵，与你缔结第一份血契', hp: 100, hpGrowth: 10, attack: 10, attackGrowth: 2, critRate: 5, critRateGrowth: 1, critDamage: 10, critDamageGrowth: 0.1, mana: 5, manaGrowth: 1, faith: 5, faithGrowth: 1, defense: 5, defenseGrowth: 1, comboThreshold: 10, comboSpeedBonus: 0.05, comboScoreBonus: 0.1, comboTimeout: 1500 },
    warrior: { id: 'char_002', name: '青铜战斧', emoji: '🪓', rarity: 'R', description: '铸魂族战器，沉睡千年的远征之斧', hp: 150, hpGrowth: 15, attack: 50, attackGrowth: 5, critRate: 15, critRateGrowth: 1.5, critDamage: 2, critDamageGrowth: 0.2, mana: 10, manaGrowth: 1, faith: 20, faithGrowth: 2, defense: 20, defenseGrowth: 2, comboThreshold: 5, comboSpeedBonus: 0.08, comboScoreBonus: 0.15, comboTimeout: 1800 },
    mage: { id: 'char_003', name: '汝窑青瓶', emoji: '🏺', rarity: 'SR', description: '瓷灵族法器，天青釉面流转千年灵韵', hp: 80, hpGrowth: 8, attack: 30, attackGrowth: 4, critRate: 20, critRateGrowth: 2, critDamage: 2.5, critDamageGrowth: 0.3, mana: 30, manaGrowth: 3, faith: 25, faithGrowth: 2.5, defense: 8, defenseGrowth: 1, comboThreshold: 8, comboSpeedBonus: 0.06, comboScoreBonus: 0.12, comboTimeout: 1600 },
    archer: { id: 'char_004', name: '秦弩灵', emoji: '🏹', rarity: 'R', description: '锋芒族远射之器，百步穿杨的秦弩之灵', hp: 100, hpGrowth: 10, attack: 60, attackGrowth: 6, critRate: 25, critRateGrowth: 2, critDamage: 2.2, critDamageGrowth: 0.2, mana: 15, manaGrowth: 1.5, faith: 15, faithGrowth: 1.5, defense: 10, defenseGrowth: 1, comboThreshold: 7, comboSpeedBonus: 0.07, comboScoreBonus: 0.13, comboTimeout: 1700 },
    dragon_knight: { id: 'char_005', name: '龙纹铜鼎', emoji: '🐉', rarity: 'SSR', description: '铸魂族重器，鼎身龙纹化作器灵战魂', hp: 200, hpGrowth: 20, attack: 80, attackGrowth: 8, critRate: 30, critRateGrowth: 3, critDamage: 3, critDamageGrowth: 0.3, mana: 20, manaGrowth: 2, faith: 30, faithGrowth: 3, defense: 35, defenseGrowth: 3, comboThreshold: 6, comboSpeedBonus: 0.1, comboScoreBonus: 0.2, comboTimeout: 2000 },
    goddess: { id: 'char_006', name: '和氏璧灵', emoji: '👸', rarity: 'UR', description: '玉魄族至宝，传国玉玺中沉睡的帝王之魂', hp: 300, hpGrowth: 30, attack: 120, attackGrowth: 12, critRate: 40, critRateGrowth: 4, critDamage: 4, critDamageGrowth: 0.4, mana: 50, manaGrowth: 5, faith: 50, faithGrowth: 5, defense: 50, defenseGrowth: 4, comboThreshold: 4, comboSpeedBonus: 0.12, comboScoreBonus: 0.25, comboTimeout: 2200 },
    assassin: { id: 'char_007', name: '鱼肠剑灵', emoji: '🗡️', rarity: 'SR', description: '锋芒族暗杀之器，藏在鱼腹中的绝命之剑', hp: 90, hpGrowth: 9, attack: 70, attackGrowth: 7, critRate: 35, critRateGrowth: 3, critDamage: 3.5, critDamageGrowth: 0.35, mana: 12, manaGrowth: 1.2, faith: 18, faithGrowth: 1.8, defense: 8, defenseGrowth: 0.8, comboThreshold: 5, comboSpeedBonus: 0.09, comboScoreBonus: 0.18, comboTimeout: 1400 },
    guardian: { id: 'char_008', name: '饕餮铜盾', emoji: '🛡️', rarity: 'R', description: '铸魂族守器，饕餮纹吞噬一切来犯之敌', hp: 250, hpGrowth: 25, attack: 25, attackGrowth: 2.5, critRate: 8, critRateGrowth: 0.8, critDamage: 1.5, critDamageGrowth: 0.15, mana: 15, manaGrowth: 1.5, faith: 25, faithGrowth: 2.5, defense: 50, defenseGrowth: 5, comboThreshold: 12, comboSpeedBonus: 0.04, comboScoreBonus: 0.08, comboTimeout: 2000 },
    summoner: { id: 'char_009', name: '敦煌卷灵', emoji: '📜', rarity: 'SSR', description: '墨魂族召唤之器，壁画飞天化为护法神将', hp: 110, hpGrowth: 11, attack: 55, attackGrowth: 5.5, critRate: 22, critRateGrowth: 2.2, critDamage: 2.8, critDamageGrowth: 0.28, mana: 40, manaGrowth: 4, faith: 35, faithGrowth: 3.5, defense: 15, defenseGrowth: 1.5, comboThreshold: 7, comboSpeedBonus: 0.08, comboScoreBonus: 0.15, comboTimeout: 1650 },
    berserker: { id: 'char_010', name: '七星龙渊', emoji: '💥', rarity: 'SSR', description: '锋芒族狂战之器，剑意暴走势不可挡', hp: 180, hpGrowth: 18, attack: 100, attackGrowth: 10, critRate: 28, critRateGrowth: 2.8, critDamage: 3.2, critDamageGrowth: 0.32, mana: 8, manaGrowth: 0.8, faith: 15, faithGrowth: 1.5, defense: 12, defenseGrowth: 1.2, comboThreshold: 4, comboSpeedBonus: 0.11, comboScoreBonus: 0.22, comboTimeout: 1500 },
    saint: { id: 'char_011', name: '兰亭序灵', emoji: '📖', rarity: 'UR', description: '墨魂族至宝，书圣遗墨化为通灵之卷', hp: 150, hpGrowth: 15, attack: 90, attackGrowth: 9, critRate: 35, critRateGrowth: 3.5, critDamage: 4.5, critDamageGrowth: 0.45, mana: 60, manaGrowth: 6, faith: 60, faithGrowth: 6, defense: 25, defenseGrowth: 2.5, comboThreshold: 5, comboSpeedBonus: 0.1, comboScoreBonus: 0.2, comboTimeout: 1800 },
    ninja: { id: 'char_012', name: '越王勾践剑', emoji: '🥷', rarity: 'SR', description: '锋芒族极速之器，千年不锈的王者之剑', hp: 85, hpGrowth: 8.5, attack: 65, attackGrowth: 6.5, critRate: 32, critRateGrowth: 3.2, critDamage: 2.8, critDamageGrowth: 0.28, mana: 10, manaGrowth: 1, faith: 20, faithGrowth: 2, defense: 6, defenseGrowth: 0.6, comboThreshold: 3, comboSpeedBonus: 0.15, comboScoreBonus: 0.16, comboTimeout: 1200 },
    priest: { id: 'char_013', name: '红山玉龙', emoji: '🙏', rarity: 'R', description: '玉魄族祭祀之器，远古先民沟通天地的媒介', hp: 120, hpGrowth: 12, attack: 35, attackGrowth: 3.5, critRate: 12, critRateGrowth: 1.2, critDamage: 1.8, critDamageGrowth: 0.18, mana: 25, manaGrowth: 2.5, faith: 40, faithGrowth: 4, defense: 12, defenseGrowth: 1.2, comboThreshold: 9, comboSpeedBonus: 0.05, comboScoreBonus: 0.11, comboTimeout: 1700 },
    paladin: { id: 'char_014', name: '鎏金铜佛', emoji: '⚖️', rarity: 'SR', description: '金翎族护法之器，佛法与战意并存的镇守者', hp: 200, hpGrowth: 20, attack: 45, attackGrowth: 4.5, critRate: 18, critRateGrowth: 1.8, critDamage: 2.3, critDamageGrowth: 0.23, mana: 20, manaGrowth: 2, faith: 35, faithGrowth: 3.5, defense: 30, defenseGrowth: 3, comboThreshold: 7, comboSpeedBonus: 0.07, comboScoreBonus: 0.14, comboTimeout: 1750 },
    hunter: { id: 'char_015', name: '吴王夫差矛', emoji: '🎯', rarity: 'R', description: '锋芒族追踪之器，锁定猎物绝不脱手', hp: 95, hpGrowth: 9.5, attack: 55, attackGrowth: 5.5, critRate: 22, critRateGrowth: 2.2, critDamage: 2.4, critDamageGrowth: 0.24, mana: 8, manaGrowth: 0.8, faith: 12, faithGrowth: 1.2, defense: 10, defenseGrowth: 1, comboThreshold: 6, comboSpeedBonus: 0.08, comboScoreBonus: 0.13, comboTimeout: 1550 },
    witch: { id: 'char_016', name: '粉彩瓷灵', emoji: '🧙‍♀️', rarity: 'SSR', description: '瓷灵族魅惑之器，以釉色迷惑众生的彩瓷', hp: 75, hpGrowth: 7.5, attack: 85, attackGrowth: 8.5, critRate: 38, critRateGrowth: 3.8, critDamage: 4, critDamageGrowth: 0.4, mana: 45, manaGrowth: 4.5, faith: 30, faithGrowth: 3, defense: 5, defenseGrowth: 0.5, comboThreshold: 4, comboSpeedBonus: 0.12, comboScoreBonus: 0.22, comboTimeout: 1300 },
    monk: { id: 'char_017', name: '兵马俑武将', emoji: '👊', rarity: 'SR', description: '铸魂族格斗之器，千年地下军团的不屈战魂', hp: 140, hpGrowth: 14, attack: 65, attackGrowth: 6.5, critRate: 28, critRateGrowth: 2.8, critDamage: 2.6, critDamageGrowth: 0.26, mana: 5, manaGrowth: 0.5, faith: 10, faithGrowth: 1, defense: 18, defenseGrowth: 1.8, comboThreshold: 4, comboSpeedBonus: 0.1, comboScoreBonus: 0.17, comboTimeout: 1400 },
    elementalist: { id: 'char_018', name: '青花缠枝瓶', emoji: '🌪️', rarity: 'SSR', description: '瓷灵族元素之器，瓶身纹饰化为风雨雷电', hp: 90, hpGrowth: 9, attack: 75, attackGrowth: 7.5, critRate: 25, critRateGrowth: 2.5, critDamage: 3.5, critDamageGrowth: 0.35, mana: 50, manaGrowth: 5, faith: 40, faithGrowth: 4, defense: 10, defenseGrowth: 1, comboThreshold: 6, comboSpeedBonus: 0.09, comboScoreBonus: 0.18, comboTimeout: 1600 },
    necromancer: { id: 'char_019', name: '司南灵', emoji: '💀', rarity: 'SSR', description: '墨魂族通灵之器，指引亡魂回归故土的上古司南', hp: 100, hpGrowth: 10, attack: 80, attackGrowth: 8, critRate: 30, critRateGrowth: 3, critDamage: 3.8, critDamageGrowth: 0.38, mana: 35, manaGrowth: 3.5, faith: 15, faithGrowth: 1.5, defense: 8, defenseGrowth: 0.8, comboThreshold: 5, comboSpeedBonus: 0.11, comboScoreBonus: 0.2, comboTimeout: 1450 },
    chronomancer: { id: 'char_020', name: '日晷灵', emoji: '⏳', rarity: 'UR', description: '金翎族时空之器，以影测时的上古天文仪', hp: 130, hpGrowth: 13, attack: 100, attackGrowth: 10, critRate: 38, critRateGrowth: 3.8, critDamage: 5, critDamageGrowth: 0.5, mana: 55, manaGrowth: 5.5, faith: 50, faithGrowth: 5, defense: 20, defenseGrowth: 2, comboThreshold: 3, comboSpeedBonus: 0.14, comboScoreBonus: 0.28, comboTimeout: 1100 },
    wanderer: { id: 'char_021', name: '碎陶行者', emoji: '🚶', rarity: 'N', description: '瓷灵族流散之器，碎片拼凑出的无名陶灵', hp: 110, hpGrowth: 11, attack: 15, attackGrowth: 1.5, critRate: 8, critRateGrowth: 0.8, critDamage: 8, critDamageGrowth: 0.08, mana: 8, manaGrowth: 0.8, faith: 8, faithGrowth: 0.8, defense: 8, defenseGrowth: 0.8, comboThreshold: 11, comboSpeedBonus: 0.04, comboScoreBonus: 0.09, comboTimeout: 1600 },
    alchemist: { id: 'char_022', name: '丹炉灵', emoji: '⚗️', rarity: 'SR', description: '铸魂族炼造之器，炼化万物的上古丹鼎之灵', hp: 105, hpGrowth: 10.5, attack: 50, attackGrowth: 5, critRate: 20, critRateGrowth: 2, critDamage: 3, critDamageGrowth: 0.3, mana: 30, manaGrowth: 3, faith: 28, faithGrowth: 2.8, defense: 12, defenseGrowth: 1.2, comboThreshold: 8, comboSpeedBonus: 0.06, comboScoreBonus: 0.15, comboTimeout: 1650 },
    vampire: { id: 'char_023', name: '血玉灵', emoji: '🧛', rarity: 'SSR', description: '玉魄族嗜血之器，战场上吸纳英魂的血沁古玉', hp: 160, hpGrowth: 16, attack: 70, attackGrowth: 7, critRate: 32, critRateGrowth: 3.2, critDamage: 3.3, critDamageGrowth: 0.33, mana: 15, manaGrowth: 1.5, faith: 5, faithGrowth: 0.5, defense: 15, defenseGrowth: 1.5, comboThreshold: 5, comboSpeedBonus: 0.1, comboScoreBonus: 0.19, comboTimeout: 1500 },
    celestial: { id: 'char_024', name: '九鼎之灵', emoji: '🌌', rarity: 'UR', description: '金翎族至高圣器，大禹铸九鼎所生的镇国器魂', hp: 280, hpGrowth: 28, attack: 130, attackGrowth: 13, critRate: 45, critRateGrowth: 4.5, critDamage: 5.5, critDamageGrowth: 0.55, mana: 70, manaGrowth: 7, faith: 70, faithGrowth: 7, defense: 40, defenseGrowth: 4, comboThreshold: 2, comboSpeedBonus: 0.16, comboScoreBonus: 0.3, comboTimeout: 1000 },
    void_emperor: { id: 'char_025', name: '噬界壶灵', emoji: '🌀', rarity: 'LR', description: '混沌邪器之主，吞噬万器之力的终极器魔', hp: 400, hpGrowth: 40, attack: 170, attackGrowth: 17, critRate: 50, critRateGrowth: 5, critDamage: 7, critDamageGrowth: 0.7, mana: 80, manaGrowth: 8, faith: 80, faithGrowth: 8, defense: 60, defenseGrowth: 6, comboThreshold: 2, comboSpeedBonus: 0.18, comboScoreBonus: 0.35, comboTimeout: 900 },
    stellar_wanderer: { id: 'char_026', name: '丝路铜驼', emoji: '🐪', rarity: 'SP', description: '金翎族远行之器，丝路驼铃中沉淀的千年灵识', hp: 260, hpGrowth: 26, attack: 135, attackGrowth: 13.5, critRate: 42, critRateGrowth: 4.2, critDamage: 5.5, critDamageGrowth: 0.55, mana: 65, manaGrowth: 6.5, faith: 65, faithGrowth: 6.5, defense: 45, defenseGrowth: 4.5, comboThreshold: 3, comboSpeedBonus: 0.15, comboScoreBonus: 0.3, comboTimeout: 1050 }
};

function getCharacterKey(charId) {
    var keys = Object.keys(Characters);
    for (var i = 0; i < keys.length; i++) {
        if (Characters[keys[i]].id === charId) return keys[i];
    }
    return 'starter';
}

export { Characters, getCharacterKey };
